---
- hosts: all
  become: yes
  tasks:
    - name: forgive me. also, TODO gradually disable it. for now the thing that complains for sure is haproxy, probs consul too. what about app? can go with infra only?
      selinux: state=disabled

    - name: "build hosts file"
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].address }} {{ item }}" state=present
      when: hostvars[item].address is defined
      with_items: "{{ groups['all'] }}"
    - name: sets hostname
      command: hostnamectl set-hostname {{ ansible_host }}

- hosts: vault
  become: yes
  tasks:
    - group:
        name: vault
        state: present
    - user:
        name: vault
        group: vault
        system: yes
        shell: /usr/sbin/nologin
    - name: copy the vault binary
      copy: src=deps/vault dest=/usr/bin/vault mode=755 owner=root group=root
    - name: copy the vault systemd unit
      copy: src=vault.service dest=/lib/systemd/system/ mode=644 owner=root group=root
      notify: reload units
    - name: ensure vault conf dir
      file: path=/etc/vault.d state=directory mode=755 owner=root group=root
    - name: copy vault config
      copy: src=vault.hcl dest=/etc/vault.d/vault.hcl mode=444 owner=vault group=vault
      notify: restart vault
    - name: copy the vault tls cert
      copy: src=deps/vault.crt dest=/etc/vault.d/vault.crt mode=444 owner=vault group=vault
      notify: restart vault
    - name: copy the vault tls key
      copy: src=deps/vault.key dest=/etc/vault.d/vault.key mode=400 owner=vault group=vault
      notify: restart vault
    - name: ensure vault storage dir
      file: path=/mnt/vault/data state=directory mode=755 owner=vault group=vault
    - name: enable and start vault
      service: name=vault state=started enabled=yes

    - name: jq
      yum: name=jq state=present
    - name: copy the root ca we signed vault's cert in the trust dir
      copy: src=deps/notanima-root.cer dest=/etc/pki/tls/certs/notanima-root.cer mode=644 owner=root group=root
      notify: update ca trust
    - name: init the vault AND SAVE THE GIVEN TOKENS, NOT RECOMMENDED TO STORE ROOT TOKEN! but in either case, BE SURE TO REVOKE IT AT SOME POINT. ALSO, THRESHOLD/SHARES 1/1 IS A MAD BAD IDEA. Also, it's possible to have keys and root token encrypted with gpg with the -pgp-keys and -root-token-pgp-key options, skipped here because automating exporting/importing keys in the vm is annoying
      command: vault init -key-threshold=1 -key-shares=1
      register: vault_init
      ignore_errors: True # to handle the fact that we init only once
    - name: save the init output for further tinkering on the box TODO REMOVEME AND GENERATE AUTH STUFF INSTEAD
      shell: echo "{{ vault_init.stdout }}" > /home/vagrant/vault-init.out
      when: vault_init | succeeded
    - name: unseal (DO NOT TRY THIS ~AT HOME~ ahem, IN PROD)
      command: vault unseal {{ vault_init.stdout_lines[0].split(' ')[-1] }}
      when: vault_init | succeeded
    - name: authenticate on vault
      command: vault auth {{ vault_init.stdout_lines[1].split(' ')[-1] }}
      when: vault_init | succeeded
    - name: mount pki backend for root ca
      command: vault mount -path=rootca pki
      when: vault_init | succeeded
    - name: generate root ca
      command: vault write rootca/root/generate/internal common_name=nomad-playground.notanima.tech
      when: vault_init | succeeded
    - name: mount pki backend for intermediate ca
      command: vault mount -path=infraca pki
      when: vault_init | succeeded
    - name: generate csr
      shell: vault write -format json infraca/intermediate/generate/internal common_name=infra.nomad-playground.notanima.tech | jq -r .data.csr
      register: infra_csr
      when: vault_init | succeeded
    - name: sign csr
      shell: vault write -format json rootca/root/sign-intermediate csr="{{ infra_csr.stdout }}" format=pem_bundle | jq -r .data.certificate
      register: infra_crt
      when: vault_init | succeeded
    - name: install intermediate signed cert
      command: vault write infraca/intermediate/set-signed certificate="{{ infra_crt.stdout }}"
      when: vault_init | succeeded
    - name: role for ansible to provision certs (lease will be used to have CT renew the cert)
      command: vault write infraca/roles/any-infra allowed_domains=infra.nomad-playground.notanima.tech allow_subdomains=true max_ttl=72h generate_lease=true
      when: vault_init | succeeded
    - name: generate a cert! TODO this demonstrate feasability, real next step is to setup auth and policies and have ct generate certs for mongo and rabbit
      shell: vault write -format json infraca/issue/any-infra common_name=todo.infra.nomad-playground.notanima.tech ttl="2h" | tee /home/vagrant/todo.crt.json
      #TODO: roles, acls, auths for ansible and/or cert-renewal consultemplates, revoke the root token, provision an "admin" account with root powers
      #TODO: set vault02 to be the ha secondary not an individually configured one, see if a consul as ha backend makes sense or it generate bootstrap-cert nightmare

  handlers:
    - name: reload units
      command: systemctl daemon-reload
    - name: restart vault
      service: name=vault state=restarted
    - name: update ca trust
      command: update-ca-trust

- hosts: infrapps
  become: yes
  tasks:
    - name: copy the consul binary
      copy: src=deps/consul dest=/usr/bin/consul mode=755 owner=root group=root
    - name: copy the consul systemd unit
      copy: src=consul.service dest=/lib/systemd/system/ mode=644 owner=root group=root
      notify: reload units
    - name: enable consul
      service: name=consul enabled=yes
    - name: ensure consul conf dir
      file: path=/etc/consul.d state=directory mode=755 owner=root group=root
    - group:
        name: consul
        state: present
    - user:
        name: consul
        group: consul
        system: yes
        shell: /usr/sbin/nologin

    - name: copy the consul-template binary
      copy: src=deps/consul-template dest=/usr/bin/consul-template mode=755 owner=root group=root

  handlers:
    - name: reload units
      command: systemctl daemon-reload

- hosts: apps
  become: yes
  tasks:
    - name: copy the consul config
      copy: src=consul-agent.json dest=/etc/consul.d/conf.json mode=644 owner=root group=root
      notify: restart consul

    - name: copy the nomad binary
      copy: src=deps/nomad dest=/usr/bin/nomad mode=755 owner=root group=root
    - name: copy the nomad config
      copy: src=nomad.hcl dest=/etc mode=644 owner=root group=root
    - name: copy the nomad systemd unit
      copy: src=nomad.service dest=/lib/systemd/system/ mode=644 owner=root group=root
      notify: reload units
    - name: start and enable nomad
      service: name=nomad state=started enabled=yes

    - name: java8
      yum:
        name: java-1.8.0-openjdk-headless.x86_64
        state: present

    - name: dnsmasq
      yum:
        name: dnsmasq
        state: present
    - name: tell NetworkManager to use the local dnsmasq
      copy: src=dns.conf dest=/etc/NetworkManager/conf.d/dns.conf mode=644 owner=root group=root
      notify: restart NetworkManager
    - name: tell NetworkManager's dnsmasq to query local consul too
      copy: src=consul-resolver dest=/etc/NetworkManager/dnsmasq.d/consul-resolver mode=644 owner=root group=root
      notify: restart NetworkManager

  handlers:
    - name: restart consul
      service: name=consul state=restarted
    - name: reload units
      command: systemctl daemon-reload
    - name: restart NetworkManager
      service: name=NetworkManager state=restarted

- hosts: infra
  become: yes
  tasks:
    - name: import rabbit and mongo signing keys
      rpm_key:
        key: "{{ item }}"
      with_items:
        - https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
        - /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    - name: mongo repo
      copy: src=mongodb-org-3.4.repo dest=/etc/yum.repos.d/ mode=644 owner=root group=root
    - name: rabbit repo
      copy: src=rabbit.repo dest=/etc/yum.repos.d/ mode=644 owner=root group=root
    - name: install all the infra sofware
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - rabbitmq-server
        - mongodb-org
        - haproxy

    - name: set the erlang cookie
      copy: src=erlang.cookie dest=/var/lib/rabbitmq/.erlang.cookie mode=400 owner=rabbitmq group=rabbitmq
    - name: copy the rabbit config
      copy: src=rabbitmq.config dest=/etc/rabbitmq/rabbitmq.config mode=644 owner=root group=root
    - name: start and enable rabbit
      service: name=rabbitmq-server state=started enabled=yes

    - name: copy the mongo config
      copy: src=mongod.conf dest=/etc/ mode=644 owner=root group=root
    - name: start and enable mongo
      service: name=mongod state=started enabled=yes

    - name: copy the haproxy config
      copy: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg mode=644 owner=root group=root
    - name: start and enable haproxy
      service: name=haproxy state=started enabled=yes

    - name: copy the consul config
      copy: src=consul-server.json dest=/etc/consul.d/conf.json mode=644 owner=root group=root
      notify: restart consul
    - name: copy the haproxy consul service definition
      copy: src=haproxy.consul.service.json dest=/etc/consul.d/haproxy.consul.service.json mode=644 owner=root group=root
      notify: restart consul

    - name: copy the consul-template systemd unit
      copy: src=consul-template.service dest=/lib/systemd/system/ mode=644 owner=root group=root
      notify: reload units
    - name: ensure consul-template conf dir
      file: path=/etc/consul-template.d state=directory mode=755 owner=root group=root
    - name: copy the consul-template config
      copy: src=consul-template.hcl dest=/etc/consul-template.d/consul-template.hcl mode=644 owner=root group=root
      notify: restart consul-template
    - name: copy the consul-template template for haproxy
      copy: src=haproxy-apps.tpl dest=/etc/consul-template.d/haproxy-apps.tpl mode=644 owner=root group=root
      notify: restart consul-template
    - name: start and enable consul-template
      service: name=consul-template state=started enabled=yes

  handlers:
    - name: restart consul
      service: name=consul state=restarted
    - name: restart consul-template
      service: name=consul-template state=restarted
    - name: reload units
      command: systemctl daemon-reload

- hosts: controller
  become: yes
  tasks:
    - name: gocd repo
      copy: src=gocd.repo dest=/etc/yum.repos.d/ mode=644 owner=root group=root
    - name: install go and requirements
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - java-1.8.0-openjdk
        - go-server
        - go-agent
    - name: provision pipeline config on go-server
      copy: src=cruise-config.xml dest=/etc/go/ mode=664 owner=go group=go
    - name: enable and start go and agent
      service: name={{ item }} state=started enabled=yes
      with_items:
        - go-server
        - go-agent

    - name: copy the lein installscript
      copy: src=deps/lein dest=/usr/bin/lein mode=755 owner=root group=root

    - name: git required for gitea
      yum:
        name: git
        state: present
    - group:
        name: gitea
        state: present
    - user:
        name: gitea
        group: gitea
    - name: ensure gitea dirs
      file: path={{ item }} state=directory mode=755 owner=gitea group=gitea
      with_items:
        - /etc/gitea
        - /var/lib/gitea
        - /var/lib/gitea/repositories
        - /var/lib/gitea/lfs
        - /var/log/gitea
    - name: copy the gitea binary
      copy: src=deps/gitea-1.3-linux-amd64 dest=/var/lib/gitea/gitea mode=755 owner=root group=root
    - name: copy the gitea systemd unit
      copy: src=gitea.service dest=/lib/systemd/system/ mode=644 owner=root group=root
      notify: reload units
    - name: ensure gitea confdir
      file: path=/etc/gitea state=directory mode=755 owner=root group=root
    - name: copy the gitea config
      copy: src=app.ini dest=/etc/gitea/app.ini mode=644 owner=root group=root
    - name: enable and start gitea
      service: name=gitea state=started enabled=yes
    - name: create user
      command: |
        /var/lib/gitea/gitea admin create-user
          --name {{ item }}
          --password {{ item }}
          --email {{ item }}@{{ item }}.com
          --config /etc/gitea/app.ini
      become_user: gitea
      with_items:
        - demo

    - name: copy the nomad binary
      copy: src=deps/nomad dest=/usr/bin/nomad mode=755 owner=root group=root

  handlers:
    - name: reload units
      command: systemctl daemon-reload
